# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: fluid
before:
  hooks:
    - sh -c "cd api && go mod tidy"
    - sh -c "cd fluid-daemon && go mod tidy"
    - sh -c "cd fluid-cli && go mod tidy"
builds:
  - id: api
    dir: api
    main: ./cmd/server
    binary: api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
  - id: fluid-daemon
    dir: fluid-daemon
    main: ./cmd/fluid-daemon
    binary: fluid-daemon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
  - id: fluid
    dir: fluid-cli
    main: ./cmd/fluid-cli
    binary: fluid
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
archives:
  - id: api
    builds:
      - api
    name_template: >-
      api_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE
  - id: fluid-daemon
    builds:
      - fluid-daemon
    name_template: >-
      fluid-daemon_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE
  - id: fluid
    builds:
      - fluid
    name_template: >-
      fluid_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE
checksum:
  name_template: checksums.txt
  algorithm: sha256
signs:
  - id: binary
    cmd: gpg
    artifacts: binary
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--armor"
      - "--pinentry-mode=loopback"
      - "--passphrase={{ .Env.GPG_PASSPHRASE }}"
      - "--local-user={{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
  - id: checksum
    cmd: gpg
    artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - "--batch"
      - "--yes"
      - "--armor"
      - "--pinentry-mode=loopback"
      - "--passphrase={{ .Env.GPG_PASSPHRASE }}"
      - "--local-user={{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - id: api
    package_name: api
    builds:
      - api
    bindir: /usr/local/bin
    vendor: "Fluid.sh"
    homepage: "https://github.com/aspectrr/fluid.sh"
    maintainer: "Collin Pfeifer <cpfeifer@madcactus.org>"
    description: "Control-plane API for fluid.sh sandbox management"
    license: "MIT"
    formats:
      - deb
      - rpm
    dependencies:
      - openssh-client
      - postgresql-client
  - id: fluid-daemon
    package_name: fluid-daemon
    builds:
      - fluid-daemon
    bindir: /usr/local/bin
    vendor: "Fluid.sh"
    homepage: "https://github.com/aspectrr/fluid.sh"
    maintainer: "Collin Pfeifer <cpfeifer@madcactus.org>"
    description: "Background daemon for managing VM sandboxes on a host"
    license: "MIT"
    formats:
      - deb
      - rpm
    dependencies:
      - openssh-client
  - id: fluid
    package_name: fluid
    builds:
      - fluid
    bindir: /usr/local/bin
    vendor: "Fluid.sh"
    homepage: "https://github.com/aspectrr/fluid.sh"
    maintainer: "Collin Pfeifer <cpfeifer@madcactus.org>"
    description: "CLI for managing fluid sandboxes"
    license: "MIT"
    formats:
      - deb
      - rpm
release:
  github:
    owner: aspectrr
    name: fluid.sh
